version: '3.8'

services:
  bank-churn-classification-end-to-end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-ml-app  
    volumes:
      - .:/app  # Mount current directory to /app inside the container
    ports:
      - "8080:8080"
